name: grokjackrag
channels:
  - pytorch  # Priority for PyTorch packages
  - conda-forge  # For other deps
dependencies:
  - python=3.12
  - pytorch=2.7.1  # Latest stable as of July 2025
  - torchvision
  - torchaudio
  - streamlit=1.37.1
  - langchain=0.2.11
  - langchain-community=0.2.10
  - langchain-huggingface=0.0.3  # Ensure this line is present
  - sentence-transformers=3.0.1
  - faiss-cpu=1.8.0
  - pypdf2=3.0.0
  - python-dotenv=1.0.0
  - openai=1.38.0
  - httpx=0.27.0  # Pin to compatible version

